import React, { useState, useRef } from "react";
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Alert,
  Share as RNShare,
  StatusBar,
} from "react-native";
import MapView, { Marker } from "react-native-maps";
import { Ionicons } from "@expo/vector-icons";
import { saveTrip } from "../../../services/supabase";
import { useTheme } from "../../../context/ThemeContext";

export default function ResultScreen({ route, navigation }) {
  const { theme } = useTheme();
  const {
    itinerary,
    destination,
    days,
    budget,
    coordinates,
    groupType,
    members,
    cityData,
    startDate,
    endDate,
    isViewingTrip = false,
  } = route.params;

  const [saving, setSaving] = useState(false);
  const mapRef = useRef(null);

  const parseItinerary = () => {
    try {
      if (!itinerary) return null;
      let raw = itinerary;
      if (typeof raw !== "string") return Array.isArray(raw) ? raw : null;
      raw = raw
        .replace(/```json/g, "")
        .replace(/```/g, "")
        .trim();
      const start = raw.indexOf("[");
      const end = raw.lastIndexOf("]");
      if (start !== -1 && end !== -1) raw = raw.substring(start, end + 1);
      return JSON.parse(raw);
    } catch {
      return null;
    }
  };

  const parsedItinerary = parseItinerary();

  const getAttractionMarkers = () => {
    if (!coordinates) return [];
    if (cityData?.attractions) {
      const withGPS = cityData.attractions.filter(
        (a) => a.latitude && a.longitude,
      );
      if (withGPS.length > 0) {
        return withGPS.slice(0, 8).map((a, index) => ({
          name: a.name,
          latitude: parseFloat(a.latitude),
          longitude: parseFloat(a.longitude),
          type: a.type,
          rating: a.rating,
          number: index + 1,
        }));
      }
    }
    if (parsedItinerary && Array.isArray(parsedItinerary)) {
      const mentioned = [];
      parsedItinerary.forEach((day) => {
        ["morning", "afternoon", "evening"].forEach((slot) => {
          if (day[slot]?.activity) mentioned.push(day[slot].activity);
        });
      });
      return [...new Set(mentioned)].slice(0, 8).map((name, index) => ({
        name,
        latitude:
          coordinates.latitude +
          ((index % 3) - 1) * 0.025 +
          (Math.random() - 0.5) * 0.01,
        longitude:
          coordinates.longitude +
          (Math.floor(index / 3) - 1) * 0.025 +
          (Math.random() - 0.5) * 0.01,
        number: index + 1,
      }));
    }
    return [];
  };

  const attractionMarkers = getAttractionMarkers();

  const recenterMap = () => {
    if (mapRef.current && coordinates) {
      const allCoords = [
        coordinates,
        ...attractionMarkers.map((m) => ({
          latitude: m.latitude,
          longitude: m.longitude,
        })),
      ];
      mapRef.current.fitToCoordinates(allCoords, {
        edgePadding: { top: 50, right: 50, bottom: 50, left: 50 },
        animated: true,
      });
    }
  };

  const calculateBudget = () => {
    if (!budget) return null;
    return {
      perDay: Math.round(budget / days),
      accommodation: Math.round(budget * 0.3),
      food: Math.round(budget * 0.4),
      activities: Math.round(budget * 0.2),
      transport: Math.round(budget * 0.1),
    };
  };
  const budgetBreakdown = calculateBudget();

  const handleSaveTrip = async () => {
    setSaving(true);
    try {
      await saveTrip(
        destination,
        days,
        itinerary,
        budget,
        groupType,
        members,
        startDate,
        endDate,
      );
      Alert.alert("Success! 🎉", "Trip saved to your collection!", [
        {
          text: "View My Trips",
          onPress: () => navigation.navigate("MainTabs", { screen: "MyTrips" }),
        },
        { text: "Plan Another", onPress: () => navigation.navigate("Planner") },
      ]);
    } catch {
      Alert.alert("Error", "Failed to save trip. Are you logged in?");
    } finally {
      setSaving(false);
    }
  };

  const handleShare = async () => {
    try {
      await RNShare.share({
        message: `🌍 My ${days}-day trip to ${destination}!\n\nBudget: $${budget} USD\nGroup: ${groupType} (${members} ${members === 1 ? "person" : "people"})\n\nGenerated by AI Travel Planner ✨`,
        title: `My Trip to ${destination}`,
      });
    } catch {}
  };

  const renderItinerary = () => {
    if (!parsedItinerary || !Array.isArray(parsedItinerary)) {
      return (
        <Text style={styles.normalText}>
          {itinerary || "No itinerary available"}
        </Text>
      );
    }
    return parsedItinerary.map((day) => (
      <View key={day.day_number} style={styles.dayCard}>
        <Text style={[styles.dayHeader, { backgroundColor: theme.primary }]}>
          📅 Day {day.day_number}
        </Text>
        {["morning", "afternoon", "evening"].map((slot) => {
          const slotData = day[slot];
          if (!slotData) return null;
          const icons = { morning: "🌅", afternoon: "☀️", evening: "🌙" };
          return (
            <View
              key={slot}
              style={[styles.slotCard, { borderLeftColor: theme.primary }]}
            >
              <Text style={[styles.timeText, { color: theme.primary }]}>
                {icons[slot]} {slot.charAt(0).toUpperCase() + slot.slice(1)}
              </Text>
              <Text style={styles.activityTitle}>{slotData.activity}</Text>
              <Text style={styles.activityDesc}>{slotData.description}</Text>
              <View style={styles.slotFooter}>
                <Text style={styles.locationText}>📍 {slotData.location}</Text>
                <Text style={styles.costText}>{slotData.cost}</Text>
              </View>
            </View>
          );
        })}
      </View>
    ));
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" />

      <View style={[styles.fixedHeader, { backgroundColor: theme.primary }]}>
        <TouchableOpacity
          style={styles.headerButton}
          onPress={() => navigation.goBack()}
        >
          <Ionicons name="arrow-back" size={24} color="#fff" />
        </TouchableOpacity>
        <View style={styles.headerCenter}>
          <Text style={styles.headerTitle}>✈️ {destination}</Text>
          <Text style={styles.headerSubtitle}>{days} Day Itinerary</Text>
        </View>
        <View style={styles.headerRight}>
          <TouchableOpacity style={styles.headerButton} onPress={handleShare}>
            <Ionicons name="share-outline" size={24} color="#fff" />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.headerButton}
            onPress={() => navigation.navigate("Profile")}
          >
            <Ionicons name="person-circle-outline" size={24} color="#fff" />
          </TouchableOpacity>
        </View>
      </View>

      <View style={styles.catalogBar}>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={{ paddingHorizontal: 4 }}
        >
          <TouchableOpacity
            style={[styles.catalogPill, { backgroundColor: theme.primary }]}
            onPress={() =>
              navigation.navigate("AccommodationDetail", {
                destination,
                days,
                members: members || 1,
                budget:
                  budgetBreakdown?.accommodation ||
                  Math.round((budget || 1000) * 0.3),
              })
            }
          >
            <Text style={styles.pillIcon}>🏨</Text>
            <View>
              <Text style={styles.pillTitle}>Stay</Text>
              <Text style={styles.pillSub}>Hotels</Text>
            </View>
            <Ionicons
              name="chevron-forward"
              size={14}
              color="rgba(255,255,255,0.7)"
            />
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.catalogPill, { backgroundColor: "#ff9800" }]}
            onPress={() =>
              navigation.navigate("FoodDetail", {
                destination,
                days,
                members: members || 1,
                budget:
                  budgetBreakdown?.food || Math.round((budget || 1000) * 0.4),
              })
            }
          >
            <Text style={styles.pillIcon}>🍽️</Text>
            <View>
              <Text style={styles.pillTitle}>Food</Text>
              <Text style={styles.pillSub}>Restaurants</Text>
            </View>
            <Ionicons
              name="chevron-forward"
              size={14}
              color="rgba(255,255,255,0.7)"
            />
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.catalogPill, { backgroundColor: "#00897b" }]}
            onPress={() =>
              navigation.navigate("ActivitiesDetail", {
                destination,
                days,
                cityData,
                budget:
                  budgetBreakdown?.activities ||
                  Math.round((budget || 1000) * 0.2),
              })
            }
          >
            <Text style={styles.pillIcon}>🎭</Text>
            <View>
              <Text style={styles.pillTitle}>Activities</Text>
              <Text style={styles.pillSub}>Things to do</Text>
            </View>
            <Ionicons
              name="chevron-forward"
              size={14}
              color="rgba(255,255,255,0.7)"
            />
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.catalogPill, { backgroundColor: "#e53935" }]}
            onPress={() =>
              navigation.navigate("TransportDetail", {
                destination,
                days,
                itinerary,
                coordinates,
                members: members || 1,
                budget:
                  budgetBreakdown?.transport ||
                  Math.round((budget || 1000) * 0.1),
              })
            }
          >
            <Text style={styles.pillIcon}>🚕</Text>
            <View>
              <Text style={styles.pillTitle}>Transport</Text>
              <Text style={styles.pillSub}>Getting around</Text>
            </View>
            <Ionicons
              name="chevron-forward"
              size={14}
              color="rgba(255,255,255,0.7)"
            />
          </TouchableOpacity>
        </ScrollView>
      </View>

      <ScrollView
        style={styles.content}
        contentContainerStyle={{ paddingTop: 165 }}
      >
        {budgetBreakdown && (
          <View style={styles.budgetCard}>
            <Text style={styles.budgetTitle}>💰 Budget Breakdown</Text>
            <Text style={styles.budgetTotal}>Total: ${budget} USD</Text>
            <Text style={styles.budgetPerDay}>
              ${budgetBreakdown.perDay}/day · {members}{" "}
              {members === 1 ? "person" : "people"} · {groupType}
            </Text>
            <View style={styles.budgetGrid}>
              {[
                {
                  icon: "🏨",
                  label: "Accommodation",
                  amount: budgetBreakdown.accommodation,
                  screen: "AccommodationDetail",
                  params: {
                    destination,
                    budget: budgetBreakdown.accommodation,
                    days,
                  },
                },
                {
                  icon: "🍽️",
                  label: "Food",
                  amount: budgetBreakdown.food,
                  screen: "FoodDetail",
                  params: { destination, budget: budgetBreakdown.food, days },
                },
                {
                  icon: "🎭",
                  label: "Activities",
                  amount: budgetBreakdown.activities,
                  screen: "ActivitiesDetail",
                  params: {
                    destination,
                    budget: budgetBreakdown.activities,
                    days,
                    cityData,
                  },
                },
                {
                  icon: "🚕",
                  label: "Transport",
                  amount: budgetBreakdown.transport,
                  screen: "TransportDetail",
                  params: {
                    destination,
                    budget: budgetBreakdown.transport,
                    days,
                    itinerary,
                    coordinates,
                  },
                },
              ].map((item) => (
                <TouchableOpacity
                  key={item.label}
                  style={styles.budgetItem}
                  onPress={() => navigation.navigate(item.screen, item.params)}
                >
                  <Text style={styles.budgetIcon}>{item.icon}</Text>
                  <Text style={styles.budgetLabel}>{item.label}</Text>
                  <Text style={styles.budgetAmount}>${item.amount}</Text>
                  <Ionicons
                    name="chevron-forward"
                    size={16}
                    color={theme.primary}
                  />
                </TouchableOpacity>
              ))}
            </View>
          </View>
        )}

        {coordinates && (
          <View style={styles.mapCard}>
            <View style={styles.mapHeader}>
              <Text style={styles.mapTitle}>📍 Your Trip Map</Text>
              <TouchableOpacity
                style={[
                  styles.recenterButton,
                  { backgroundColor: theme.primary },
                ]}
                onPress={recenterMap}
              >
                <Text style={styles.recenterButtonText}>🎯 Recenter</Text>
              </TouchableOpacity>
            </View>
            <MapView
              ref={mapRef}
              style={styles.map}
              initialRegion={{
                latitude: coordinates.latitude,
                longitude: coordinates.longitude,
                latitudeDelta: 0.15,
                longitudeDelta: 0.15,
              }}
              onMapReady={recenterMap}
              showsUserLocation
              showsMyLocationButton
              showsCompass
              zoomEnabled
              showsBuildings={false}
              showsIndoors={false}
            >
              <Marker
                coordinate={coordinates}
                title={destination}
                description="Your destination"
                pinColor="red"
              />
              {attractionMarkers.map((marker, index) => (
                <Marker
                  key={index}
                  coordinate={{
                    latitude: marker.latitude,
                    longitude: marker.longitude,
                  }}
                  title={marker.name}
                  description={
                    marker.type
                      ? `${marker.type} · ⭐ ${marker.rating}`
                      : `Stop ${marker.number}`
                  }
                >
                  <View
                    style={[
                      styles.customMarker,
                      { backgroundColor: theme.primary },
                    ]}
                  >
                    <Text style={styles.markerText}>{marker.number}</Text>
                  </View>
                </Marker>
              ))}
            </MapView>
            <View style={styles.legend}>
              <View style={styles.legendItem}>
                <View style={[styles.legendDot, { backgroundColor: "red" }]} />
                <Text style={styles.legendText}>Destination</Text>
              </View>
              <View style={styles.legendItem}>
                <View
                  style={[
                    styles.numberedDot,
                    { backgroundColor: theme.primary },
                  ]}
                >
                  <Text style={styles.numberedDotText}>1</Text>
                </View>
                <Text style={styles.legendText}>
                  Attractions ({attractionMarkers.length})
                </Text>
              </View>
            </View>
          </View>
        )}

        <View style={styles.itineraryCard}>{renderItinerary()}</View>

        {!isViewingTrip && (
          <TouchableOpacity
            style={[styles.saveButton, saving && styles.buttonDisabled]}
            onPress={handleSaveTrip}
            disabled={saving}
          >
            <Text style={styles.saveButtonText}>
              {saving ? "Saving..." : "💾 Save Trip"}
            </Text>
          </TouchableOpacity>
        )}

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  fixedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 40,
    paddingHorizontal: 16,
    zIndex: 1000,
    elevation: 8,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerCenter: { flex: 1, alignItems: "center", paddingHorizontal: 16 },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: "#fff" },
  headerSubtitle: { fontSize: 14, color: "#e0e0e0" },
  headerRight: { flexDirection: "row", gap: 8 },
  content: { flex: 1, padding: 20 },
  catalogBar: {
    position: "absolute",
    top: 100,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 12,
    zIndex: 999,
    elevation: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  catalogPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    marginRight: 10,
    gap: 8,
    minWidth: 130,
    elevation: 3,
  },
  pillIcon: { fontSize: 22 },
  pillTitle: { fontSize: 13, fontWeight: "700", color: "#fff" },
  pillSub: { fontSize: 11, color: "rgba(255,255,255,0.8)" },
  budgetCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    elevation: 4,
    borderLeftWidth: 4,
    borderLeftColor: "#00c853",
  },
  budgetTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  budgetTotal: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#00c853",
    marginBottom: 4,
  },
  budgetPerDay: { fontSize: 14, color: "#666", marginBottom: 16 },
  budgetGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  budgetItem: {
    width: "48%",
    backgroundColor: "#f9f9f9",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e0e0e0",
  },
  budgetIcon: { fontSize: 36, marginBottom: 8 },
  budgetLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 4,
    fontWeight: "600",
  },
  budgetAmount: { fontSize: 18, fontWeight: "bold", color: "#333" },
  mapCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    elevation: 4,
  },
  mapHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  mapTitle: { fontSize: 18, fontWeight: "bold", color: "#333" },
  recenterButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  recenterButtonText: { color: "#fff", fontSize: 12, fontWeight: "600" },
  map: { width: "100%", height: 300, borderRadius: 12 },
  customMarker: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#fff",
    elevation: 5,
  },
  markerText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  legend: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  legendItem: { flexDirection: "row", alignItems: "center" },
  legendDot: { width: 12, height: 12, borderRadius: 6, marginRight: 6 },
  numberedDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
  },
  numberedDotText: { color: "#fff", fontSize: 10, fontWeight: "bold" },
  legendText: { fontSize: 12, color: "#666" },
  itineraryCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    elevation: 4,
  },
  dayCard: { marginBottom: 20, borderRadius: 12, overflow: "hidden" },
  dayHeader: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  slotCard: {
    backgroundColor: "#f9f9f9",
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    borderLeftWidth: 3,
  },
  timeText: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  activityTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  activityDesc: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
    marginBottom: 8,
  },
  slotFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  locationText: { fontSize: 12, color: "#888", flex: 1 },
  costText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#00c853",
    backgroundColor: "#e8f5e9",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  normalText: { fontSize: 15, lineHeight: 24, color: "#555" },
  saveButton: {
    backgroundColor: "#00c853",
    padding: 18,
    borderRadius: 16,
    alignItems: "center",
    elevation: 4,
  },
  saveButtonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  buttonDisabled: { backgroundColor: "#999" },
});
